# Config file for automatic testing at travis-ci.org

language: python
python:
  - 3.7
# - 3.6

before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov
# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
    - pip install ".[test]"
script: pytest

after_success:
    - codecov
    - coveralls

# Assuming you have installed the travis-ci CLI tool, after you
# create the Github repo and add it to Travis, run the
# following command to finish PyPI deployment setup:
# $ travis encrypt --add deploy.password
#deploy:
#  provider: pypi
#  distributions: sdist bdist_wheel
#  user: catana-research
#  password:
#    secure: asdasdadsadasd
#  on:
#    tags: true
#    repo: catana-research/project_test
#    python: 3.7
