# Config file for automatic testing at travis-ci.org

language: python
python:
  - 3.7
# - 3.6

install:
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls
  - pip install -r requirements-dev.txt
script:
  - flake8 project_test --statistics --show-source
  - pytest --cov=project_test/
  - make -C docs html

after_success:
   # - codecov
    - coveralls


# Assuming you have installed the travis-ci CLI tool, after you
# create the Github repo and add it to Travis, run the
# following command to finish PyPI deployment setup:
# $ travis encrypt --add deploy.password
#deploy:
#  provider: pypi
#  distributions: sdist bdist_wheel
#  user: catana-research
#  password:
#    secure: asdasdadsadasd
#  on:
#    tags: true
#    repo: catana-research/project_test
#    python: 3.7
